# Generated by Django 4.2.3 on 2023-07-21 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], max_length=20)),
                ('set', models.CharField(max_length=15)),
                ('rice', models.CharField(max_length=100)),
                ('main_dish', models.CharField(max_length=100)),
                ('side_dish', models.CharField(max_length=100)),
                ('second_side_dish', models.CharField(blank=True, max_length=100)),
                ('dessert', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.CharField(default='GOSET', max_length=100)),
                ('main_dish', models.CharField(max_length=100)),
                ('rice', models.CharField(default='Plain Rice', max_length=100)),
                ('side_dish', models.CharField(max_length=100)),
                ('second_side_dish', models.CharField(max_length=100)),
                ('dessert', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
